### ISSUE TITLE
Please add powerline font support

### ISSUE THREAD

**Issue by yangnin** [intel/intel-one-mono#21] opened 2023-06-12 01:31 UTC
vim/tmux have some special fonts coding to display symbol. It will be great to have a font patch to support.
e.g.
\uE0B0
\uE0B1
\uE0B2
\uE0B3
w support
![image](https://github.com/intel/intel-one-mono/assets/41041332/18daffe3-4103-49a6-a3b1-02e7e9bff900)

w/o support
![image](https://github.com/intel/intel-one-mono/assets/41041332/a533adab-efe4-4708-bf00-a4dd2b27ebdb)

Thanks!

**Comment by TobiasFrereJones** [comment] 2023-06-23 20:12
Duplicate of #9

**Closed by TobiasFrereJones** 2023-06-23 20:12 UTC

**Comment by natecox** [comment] 2023-07-25 18:59
@TobiasFrereJones I'm not sure this is actually a duplicate, the linked issue is asking for ligature support, where this is a much smaller request to get power line unicodes added.

**Comment by yangning1368** [comment] 2024-08-28 07:31
@TobiasFrereJones   Hi, I check the latest release version, this issue still exists and #9 has been closed. When do we add this small request to repo?
