### ISSUE TITLE
Missing box drawing characters

### ISSUE THREAD

**Issue by galdor** [intel/intel-one-mono#4] opened 2023-05-13 14:24 UTC
It would be nice to have common box drawing characters.
From the well known UTF-8 test file:

```
Box drawing alignment tests:                                          █
                                                                      ▉
  ╔══╦══╗  ┌──┬──┐  ╭──┬──╮  ╭──┬──╮  ┏━━┳━━┓  ┎┒┏┑   ╷  ╻ ┏┯┓ ┌┰┐    ▊ ╱╲╱╲╳╳╳
  ║┌─╨─┐║  │╔═╧═╗│  │╒═╪═╕│  │╓─╁─╖│  ┃┌─╂─┐┃  ┗╃╄┙  ╶┼╴╺╋╸┠┼┨ ┝╋┥    ▋ ╲╱╲╱╳╳╳
  ║│╲ ╱│║  │║   ║│  ││ │ ││  │║ ┃ ║│  ┃│ ╿ │┃  ┍╅╆┓   ╵  ╹ ┗┷┛ └┸┘    ▌ ╱╲╱╲╳╳╳
  ╠╡ ╳ ╞╣  ├╢   ╟┤  ├┼─┼─┼┤  ├╫─╂─╫┤  ┣┿╾┼╼┿┫  ┕┛┖┚     ┌┄┄┐ ╎ ┏┅┅┓ ┋ ▍ ╲╱╲╱╳╳╳
  ║│╱ ╲│║  │║   ║│  ││ │ ││  │║ ┃ ║│  ┃│ ╽ │┃  ░░▒▒▓▓██ ┊  ┆ ╎ ╏  ┇ ┋ ▎
  ║└─╥─┘║  │╚═╤═╝│  │╘═╪═╛│  │╙─╀─╜│  ┃└─╂─┘┃  ░░▒▒▓▓██ ┊  ┆ ╎ ╏  ┇ ┋ ▏
  ╚══╩══╝  └──┴──┘  ╰──┴──╯  ╰──┴──╯  ┗━━┻━━┛           └╌╌┘ ╎ ┗╍╍┛ ┋  ▁▂▃▄▅▆▇█

```

Note that web browsers does not display them correctly in GitHub due to a 1.45 line height. With a 1.0 line height, they are correctly aligned.

**Comment by MatthewTurrini** [comment] 2023-05-20 17:15
Noted. Looking into this.

**Comment by DawnDawnKeppel** [comment] 2023-06-14 10:47
Noted. Looking into this

**Comment by iisfaq** [comment] 2023-07-01 20:50
That would be nice - I use some of these box chatracters for comments in the my source. I use [ascii flow](https://asciiflow.com/#/) to generate the boxes.

**Comment by FredShallcrass** [comment] 2024-03-13 16:50
Hello box drawing character enthusiasts.

We are in the process of adding support for programming ligatures and box drawing characters to Intel One Mono. We are currently at a BETA stage which is a good time to get feedback on the character set and forms.

In this zip file is a beta build which you can install to try out the new character set. If you are trying out the ligatures, there are a few things to note:

Rendering – There are some rendering issues with overlapping glyphs in some of the programming ligatures. This will be addressed in the final build.

Feedback Timeline – In order to make sure your feedback is heard, please post any thoughts in this thread by the end of the week.

Calt Feature – In this beta build, the ligatures will be activated by default through the calt feature. This will ensure they are easy to test, but in the final build the ligatures will be accessed though stylistic sets in order to ensure those who do not use ligatures can continue to have them off by default.

Thank you for your time and thoughts!


[Intel One Mono Programming Ligature BETA.zip](https://github.com/intel/intel-one-mono/files/14591002/Intel.One.Mono.Programming.Ligature.BETA.zip)

**Comment by galdor** [comment] 2024-03-14 08:43
With the font files you posted in xterm (same result in Emacs):

![intel-one-mono](https://github.com/intel/intel-one-mono/assets/37804/407721be-6c3a-4c91-8925-248c3bfbc4ba)

There are tiny issues, the glyphes don't perfectly connect (maybe some hinting issue), but they very rarely do (MonoLisa is the best at it), but this is very good in general. I also suspect that the characters highlighted on this screen shot should be diagonally connected to form a larger cross; again, something a lot of typefaces get wrong.

**Comment by FredShallcrass** [comment] 2024-03-14 23:35
Thank you for trying this out!

What operating system are you using? Do you have a non default line height set Emacs?

When I test the fonts in Emacs, the straight box glyphs align vertically without a gap. 

The diagonal alignment is great feedback, thanks, I wasn't sure what the expected behaviour was here because as you note, a lot of fonts do not align these vertically. We will fix this.

**Comment by galdor** [comment] 2024-03-15 09:17
The tiny spaces only appear in Xterm, not in Emacs. Not a big deal though, lots of fonts have this very problem, I suspect hinting subtleties.

As for diagonal alignment, most typefaces do not even provide the glyphs. Both PragmataPro and Berkeley Mono have the correct ones though.

Environment:
- Linux
- Freetype 2.13.2
- Xft configuration:
  ```
  Xft.dpi: 163
  Xft.antialias: 1
  Xft.hinting: 1
  Xft.autohint: 0
  Xft.lcdfilter: lcddefault
  Xft.hintstyle: hintsfull
  Xft.rgba: rgb
  ```

In Emacs:

![emacs](https://github.com/intel/intel-one-mono/assets/37804/ecc8c2b5-f5b1-40bd-b72e-c061eaf81f24)

**Closed** 2024-07-26 14:50 UTC
