### ISSUE TITLE
Please add Thin, ExtraLight variations.

### ISSUE THREAD

**Issue by jasonm23** [intel/intel-one-mono#7] opened 2023-05-16 01:05 UTC
Due to optic/vision issues (Light sensitivity), I experience an exponentially better viewing/writing experience when I use a typeface that is extremely thin (IBM Plex Mono Thin for example) however the choices available are very limited.

Please consider adding Thin and/or ExtraLight variations.

**Comment by MatthewTurrini** [comment] 2023-05-20 17:12
Thanks for the feedback. We'll review your request and consider.

**Comment by DawnDawnKeppel** [comment] 2023-06-14 10:46
nice

**Comment by TobiasFrereJones** [comment] 2023-06-30 20:14
Duplicate of #38

**Closed by TobiasFrereJones** 2023-06-30 20:14 UTC
