### ISSUE TITLE
Windows Defender finding Trojan:Script/Wacatac.B!ml in the TTF download

### ISSUE THREAD

**Issue by onlynickleft** [intel/intel-one-mono#24] opened 2023-06-12 23:23 UTC
When downloading the TTF version of the font, Windows Defender detects Trojan:Script/Wacatac.B!ml and prevents download.

**Comment by sno2** [comment] 2023-06-13 01:37
Both 7zip and WinRaR flag the zip file as containing a virus or potentially unwanted software.

**Comment by TobiasFrereJones** [comment] 2023-06-23 19:51
Thank you for taking time to file this issue. From what we can tell on our end, we don't believe there to be any malware in the release folders. We have run the folder through VirusTotal.com, which detected zero malware. We also looked for hidden files through the terminal (on a Mac) and found no such scripts. Finally, we opened the release folders on a separate Windows machine running the latest version of Windows 11 (Version 22H2, OS Build 22621.1413), and scanned the folder using the latest Windows Defender (as of June 13, 2023), and we could not reproduce the issue.

We’ll close the issue for now, because we don’t think the problem is on our end. It could be a false positive from Windows or another virus scanner, or perhaps the script is coming from elsewhere on your system. However, if you (or someone else) continue to experience this, please let us know, along with a few details about your Windows version. You can find this in *Settings > System > About*, then *Windows Specifications*. From there, please copy the *Windows Edition*, *Version*, and *OS Build*, and paste the info here. Thanks again!

**Closed by TobiasFrereJones** 2023-06-23 19:51 UTC
