### ISSUE TITLE
Tab characters are not aligned

### ISSUE THREAD

**Issue by Hypnoes** [intel/intel-one-mono#55] opened 2023-10-23 05:34 UTC
<img width="901" alt="image" src="https://github.com/intel/intel-one-mono/assets/13956546/13e7751a-cef4-4b82-b997-4318081961ab">

Fira Code：

<img width="697" alt="image" src="https://github.com/intel/intel-one-mono/assets/13956546/6445ef92-9bd4-47c7-a197-9395639b2f29">

**Comment by FredShallcrass** [comment] 2023-10-23 16:20
Hello, 

Can you please post the underlying text string so we can investigate what is happening here?

We suspect that the text string uses box drawing glyphs which are not yet supported in the font and all falling back to another font with a different set width.  

Thanks

**Comment by Hypnoes** [comment] 2023-10-27 05:00
┌────────────────┬─────────────────────┬───────────┐
│ mesh           ┆ dt                  ┆ cv        │
│ ---            ┆ ---                 ┆ ---       │
│ str            ┆ datetime[μs]        ┆ f64       │
╞════════════════╪═════════════════════╪═══════════╡
│ GDVR|GDKF|GDXO ┆ 2023-09-26 09:38:00 ┆ 23.25     │
│ GDVR|GDKF|GDXO ┆ 2023-09-26 17:39:00 ┆ 24.538462 │
│ GDVR|GDKF|GDXO ┆ 2023-10-10 17:43:00 ┆ 36.857143 │
│ GDVR|GDKF|GDXO ┆ 2023-10-10 17:44:00 ┆ 39.235294 │
│ …              ┆ …                   ┆ …         │
│ GZYN|YNKX|YNSV ┆ 2023-10-16 14:17:00 ┆ 15.333333 │
│ JXSR|JXXC|JXYZ ┆ 2023-10-16 14:17:00 ┆ 27.933333 │
│ JXXD|HNBQ|JXXT ┆ 2023-10-16 14:17:00 ┆ 15.09375  │
│ JXTG|JXWV|JXYA ┆ 2023-10-16 14:17:00 ┆ 24.857143 │
└────────────────┴─────────────────────┴───────────┘

**Comment by Hypnoes** [comment] 2023-10-27 05:05
```
┌──────────┬────────────────┬──────────┬──────────┬──────────┬──────────┬──────────┬─────────────────────┐
│ column_1 ┆ column_2       ┆ column_3 ┆ column_4 ┆ column_5 ┆ column_6 ┆ column_7 ┆ column_8            │
│ ---      ┆ ---            ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---                 │
│ i64      ┆ str            ┆ i64      ┆ i64      ┆ f64      ┆ f64      ┆ f64      ┆ str                 │
╞══════════╪════════════════╪══════════╪══════════╪══════════╪══════════╪══════════╪═════════════════════╡
│ 1        ┆ HNHG|HNHJ|HNJA ┆ 28       ┆ 19       ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 2023-09-26 17:38:32 │
│ 2        ┆ HNHG|HNHJ|HNJA ┆ 32       ┆ 32       ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 2023-09-26 17:38:32 │
│ 3        ┆ HNHG|HNHJ|HNJA ┆ 99       ┆ 5        ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 2023-09-26 17:38:32 │
│ 4        ┆ HNHG|HNHJ|HNJA ┆ 103      ┆ 17       ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 2023-09-26 17:38:32 │
│ …        ┆ …              ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …                   │
│ 181936   ┆ HNGU|HNGA|HNGV ┆ 40       ┆ 12       ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 2023-10-16 14:16:42 │
│ 181937   ┆ HNGU|HNGA|HNGV ┆ 41       ┆ 4        ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 2023-10-16 14:16:42 │
│ 181938   ┆ HNGU|HNGA|HNGV ┆ 43       ┆ 5        ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 2023-10-16 14:16:42 │
│ 181939   ┆ HNGU|HNGA|HNGV ┆ 68       ┆ 14       ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 2023-10-16 14:16:42 │
└──────────┴────────────────┴──────────┴──────────┴──────────┴──────────┴──────────┴─────────────────────┘
```

**Comment by Hypnoes** [comment] 2023-10-27 05:07
<img width="844" alt="image" src="https://github.com/intel/intel-one-mono/assets/13956546/f5a2c73d-e051-4d59-9688-18bd8bfe2f8f">

Interesting, I'm thinking that is a vscode rendering problem.

**Comment by FredShallcrass** [comment] 2023-10-31 20:25
Hello, this alignment difference seems to be caused by the face that box drawing glyphs are not yet supported in Intel One Mono. This may be part of a future release, but for now I am going to close this issue because Issue #4 already covers this.

**Closed by FredShallcrass** 2023-10-31 20:25 UTC
